### ISSUE TITLE
quotes not allowed in description string log10 error and fix

### ISSUE THREAD

**Issue by davidchatting** [CHItA/ros-docker#1]
I was getting the error described here: https://github.com/tum-vision/lsd_slam/issues/270 (Exception: quotes not allowed in description string log10 of threshold on point's variance, in the respective keyframe's scale.)

So I edited the Docker file to point to > https://github.com/rossbar/lsd_slam instead which fixed the problem

David

**Comment by CHItA** [comment]
Thanks for letting me know, if I understand correctly you modified [this line](https://github.com/CHItA/ros-docker/blob/master/images/lsd-slam/Dockerfile#L27) to point to the repo you linked to, is that correct?

**Comment by trn84** [comment]
I have the same issue

**Comment by CHItA** [comment]
I still haven't found the time to update the image, however, it might fix the problem if you replace [this line](https://github.com/CHItA/ros-docker/blob/master/images/lsd-slam/Dockerfile#L27) with 
```
git clone  https://github.com/rossbar/lsd_slam.git lsd_slam
```

I hope this helps.
